# Travis-CI Build for Boo
# see travis-ci.org for details

language: csharp

# Choose a compatible Mono version
mono:
  - 4.2.1

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "secure: dHirC1bsjCl+PDSxBY+9gukM78RI7HFeeJ4RL4eXq0iurngGVPd2Ks26bXs9uB4YPvks/kH0egoFStCL9Sb/e+aBusEEFk0cf/e9+TuVkj43o4BqXTYLoFmVMvrzDX9HoKbkopIYcWfMYHBcVXkTn60vJdCh8xz6J4qV0Pw2edRq58aS3EpZTzhl1apJj+8qTeAnwJLJ39ypjB5vE7r/PBZy1viFuKSEF/H4v31WIB1I2RRkWDHHNjWh+KvY9P+KqaGOD/fEa6U6suvOyqOpOvJTRpK7Q9iq4NNj5pg6QGlpFUiJPx9fCahC7LIYXGRUkSqMbvasANu40VnGh2ZQBJm6YC+GE11FGXTbfdikm43j1cMSNj4k/Cpk4DTFWFkY2DcE9KRG7TR5BhmhEzvw2rouTzCor20tD9iyDfkIvogyMz6ecVxay4DFKplqb+1FZDA/6Eyvcv0X4iHskZhIi2A2RqCrAMzYGIK3cLiFPMBw1WAfZXG1LZ9tJTHzcII4WUi0aRd2lGs8VaiWUyg/zeDmrJwV2TCmlpXUAnujMA0bUN2M5q/KSlniTaPAC5NA6HXkALzaPHSAxmWcxawWrLx5di9sQqUxPdKIgWsY5sMnyQ1mAKcrjtR6oUJj3s+aEzl9wW1RtPMTrTH5b6hgh58FfpfxQ/2KaucIWKJJpiE="
    - EnableNuGetPackageRestore=true
    - NUNIT_VERSION="2.6.3"
    - NANT_COMMIT="e3644541bf083d8e33f450bfbd1a4147e494769c"
    - MONO_PATH=mono
    - MCS_PATH=mcs

install:
  - ./build-tools/bootstrap

script:
 - ./ci

after_success:
 # Generate a simple distribution file
 - popd
 - cp -r build boo-latest
 - zip boo-latest.zip boo-latest/*
 - mono --debug build/booi.exe scripts/github-release.boo -- unstable boo-latest.zip
 
deploy:
  provider: releases
  api_key: "secure: dHirC1bsjCl+PDSxBY+9gukM78RI7HFeeJ4RL4eXq0iurngGVPd2Ks26bXs9uB4YPvks/kH0egoFStCL9Sb/e+aBusEEFk0cf/e9+TuVkj43o4BqXTYLoFmVMvrzDX9HoKbkopIYcWfMYHBcVXkTn60vJdCh8xz6J4qV0Pw2edRq58aS3EpZTzhl1apJj+8qTeAnwJLJ39ypjB5vE7r/PBZy1viFuKSEF/H4v31WIB1I2RRkWDHHNjWh+KvY9P+KqaGOD/fEa6U6suvOyqOpOvJTRpK7Q9iq4NNj5pg6QGlpFUiJPx9fCahC7LIYXGRUkSqMbvasANu40VnGh2ZQBJm6YC+GE11FGXTbfdikm43j1cMSNj4k/Cpk4DTFWFkY2DcE9KRG7TR5BhmhEzvw2rouTzCor20tD9iyDfkIvogyMz6ecVxay4DFKplqb+1FZDA/6Eyvcv0X4iHskZhIi2A2RqCrAMzYGIK3cLiFPMBw1WAfZXG1LZ9tJTHzcII4WUi0aRd2lGs8VaiWUyg/zeDmrJwV2TCmlpXUAnujMA0bUN2M5q/KSlniTaPAC5NA6HXkALzaPHSAxmWcxawWrLx5di9sQqUxPdKIgWsY5sMnyQ1mAKcrjtR6oUJj3s+aEzl9wW1RtPMTrTH5b6hgh58FfpfxQ/2KaucIWKJJpiE="
  file: "boo-latest.zip"
  skip_cleanup: true
  on:
    repo: danijepg/boo
