# Travis-CI Build for Boo
# see travis-ci.org for details

language: csharp

# Choose a compatible Mono version
mono:
  - 4.2.1

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "WtlJfRgv+SakyU28p9agDZ6NMqAHVzLhqSYpuivySv9gWw/RLkEzCeVFPg1sQ9WsqFvEVYwt5Hcasb2U1NydkUdk6tasqy3D+vtKHbisg8jFy2Wdxffu8b5p8laMB7qKCtaBUyDZhvL2ZKXBYDxtYzut/+nSx6V3bMh/FIvN7Fs="
    - EnableNuGetPackageRestore=true
    - NUNIT_VERSION="2.6.3"
    - NANT_COMMIT="e3644541bf083d8e33f450bfbd1a4147e494769c"
    - MONO_PATH=mono
    - MCS_PATH=mcs

install:
  - ./build-tools/bootstrap

script:
 - ./ci

after_success:
 # Generate a simple distribution file
 - popd
 - cp -r build boo-latest
 - zip boo-latest.zip boo-latest/*
 - mono --debug build/booi.exe scripts/github-release.boo -- unstable boo-latest.zip
 
deploy:
  provider: releases
  api_key: "E/UvPtj7htSsc+WSSyLDMB2jeXuuD3ZEqbsp9/M7PszCVqN8Cbs6GaP+u4O4q/+VFlGhOjYmehfd7NGmCPgFlxKnb21u6vzqbCWngoKNv6PvwtXwYmgsuV/IO/D+JraF1qpMkX+FsQwaqhubP3Am3UCx0l1PeYoOPWjxivjZg0szDuZXHIMXVkHpBwh/HJWEkzy5O7Smwy+gsQQKjBB127obqfXUNc/hiUTNLd9N6ToIgTitvrlWlvGILVlLdNsx1Je7GR2wYBbG0u4jG1yFRU8nSCtC+fIDtMGrpxhws6hhvH7ShDgAYlLfbVFUvt+3bZVO+30/QyBJ+myzE+cPxLge3RhDvXsaWEslLiwqTEpny4+0YrCbaWTv2APPycDlfqyDhINpZgOOoTypB+UDF1cuMOWyxjShBROeEgb3HQp74eUg7pkeEN6935DSvFt4YuRRlS6nS9fNctPWJxAZh0WacN7UDl+CkkOo9UFS2yMXG5pUjB04l/KNiZddrOcO6ap0TOm2y/vtk2bpsJzoK/a0GOWQl4eQCt4Bd74/hkRU7j4moffe+JTQw1KTHzCi+Qjjc2AFSikCns73WL7vtj6k6HFVGjOwYhhvT/sVa7atJN0p+3S3jq7t/x56UEj4QS3aWQFSpHRQHfqg+ptQz4rzEdX6B7f3xmBD9SRXqaU="
  file: "boo-latest.zip"
  skip_cleanup: true
  on:
    repo: danijepg/boo
