# Travis-CI Build for Boo
# see travis-ci.org for details

language: csharp

# Choose a compatible Mono version
mono:
  - 4.2.1

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "WtlJfRgv+SakyU28p9agDZ6NMqAHVzLhqSYpuivySv9gWw/RLkEzCeVFPg1sQ9WsqFvEVYwt5Hcasb2U1NydkUdk6tasqy3D+vtKHbisg8jFy2Wdxffu8b5p8laMB7qKCtaBUyDZhvL2ZKXBYDxtYzut/+nSx6V3bMh/FIvN7Fs="
    - EnableNuGetPackageRestore=true
    - NUNIT_VERSION="2.6.3"
    - NANT_COMMIT="e3644541bf083d8e33f450bfbd1a4147e494769c"
    - MONO_PATH=mono
    - MCS_PATH=mcs

install:
  - ./build-tools/bootstrap

script:
 - ./ci

after_success:
 # Generate a simple distribution file
 - popd
 - cp -r build boo-latest
 - zip boo-latest.zip boo-latest/*
 - mono --debug build/booi.exe scripts/github-release.boo -- unstable boo-latest.zip
 
deploy:
  provider: releases
  api_key: "CRKBZhWBR+usdtKf/VcqA3bdekgBMZWCMeyPlXsqKAEsdha8yz7eDmZTpAaQAfNUAwT4qMA3UZXqWK9nnODSiOgdyzJSJkbp7j4QrJ9CnHfWcZHVTPhblfZGgroad40xEIh9UhchpmXAnr4lzKeRhjd5BMfSs8UdiZH9n/ZvcklbnAlf1AKAGALmDmV5eS3DgX8kUbobFovcQyuznSZa1wB9/zERmRTgmkRHDhse3rUL5anrXOk1Bz1Os8ARYbpYPckNHltZhzF8G0rtdaLUxqciap8A4EXxf1oMqc6zo49XlHa9FgZUuKmbCztkrbGM6yPMzrA/znJ3jDG5fovvpOr1OrWyeyQk8NxyJ/LtAqmVHKLKsjStg5NNmVkWx4j94jTX7FVNCs/KJrAwnLrNBDKXpfai50SMCNpGFKESKxn1Wx/7w0Lr8G6iWdm4BGaySAxszPG/Gudwa+U7H7Wxp3sXtSy2RAvSgvE2ryzu3V/8NvPN6grO29/B26tY3/MGKPnP3FHmZKY1JF54a4JtvSE+zEIArozIJZxArXB46rrQSG3rSHhIZ6lYeFawV7CHIUbM80qz7DuFF8idX6S3iN8O2IC2pfdJ6IRAFcg4YRmZL3gzDbAY9Z8zGHpsbw60N4bKmri9/F4t+1T0Pvf/TYYbGvLyCK6Qz52aGfYYauw="
  file: "boo-latest.zip"
  skip_cleanup: true
  on:
    repo: danijepg/boo
